python:
  - "2.7"
  - "3.5"
before_install:
  - sudo pip install pathtools
services:
  - rabbitmq
install:
  - pip install --user -r requirements-dev.txt
script: ./run_integration_tests.sh > /dev/null ; ./run_integration_tests.sh
virtualenv:
    system_site_packages: true
