python:
  - "2.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-pathtools
services:
  - rabbitmq
install:
  - pip install -r requirements-dev.txt
script: ./run_integration_tests.sh
virtualenv:
    system_site_packages: true
